const sections = {
  core: 'core',
  canBuild: 'canBuild_',
  graphics: 'graphics',
  attack: 'attack',
  turret: 'turret_',
  projectile: 'projectile_',
  movement: 'movement',
  ai: 'ai',
  arm: 'arm_',
  leg: 'leg_',
  attachment: 'attachment_',
  effect: 'effect_',
  animation: 'animation_',
  action: 'action_',
  hiddenAction: 'hiddenAction_',
  placementRule: 'placementRule_',
  resource: 'resource_',
  global: 'global_resource_',
  decal: 'decal_',
  comment: 'comment_',
  template: 'template_',
}

const values = {
  //Common Values
  bool: ['true', 'false'],
  logicBoolean: ['true', 'false', 'if', 'and', 'or'],

  //Logic Values
  unitRef: [
    'self',
    'attachment',
    'transporting',
    'attacking',
    'lastDamagedBy',
    'parent',
    'activeWaypointTarget',
    'customTarget1',
    'customTarget2',
    'nearestUnit',
    'globalSearchForFirstUnit',
    'nullUnit',
    'null',
    'getAsMarker()',
    'getOffsetAbsolute()',
    'getOffsetRelative()',
    'createMarker()',
    "readUnitMemory('',type='')",
  ],

  boolRef: [
    'isUnderwater()',
    'underwater()',
    'ground()',
    'isAtGroundHeight()',
    'flying()',
    'isFlying()',
    'isMoving()',
    'isAtTopSpeed()',
    'isInWater()',
    'isOverwater()',
    'isOverLiquid()',
    'isOverClift()',
    'isOverPassableTile()',
    'isOverOpenLand()',
    'hasResources()',
    'resource()',
    'isResourceLargerThan()',
    'isEnergyRecharging()',
    'isAmmoEmpty()',
    'isEnergyFull()',
    'isEnergyEmpty()',
    'hasFlag()',
    'hasTags()',
    'globalTeamTags()',
    'isAttacking()',
    'hasActiveWaypoint()',
    'transportingUnitWithTags()',
    'isTransportUnloading()',
    'hasParent()',
    'hasTakenDamage()',
    'isOnNeutralTeam()',
    'hasUnitInTeam()',
    'noUnitInTeam()',
    'isInMap()',
    'isReversing()',
    'isControlledByAI()',
    'isAtTopSpeed()',
    'completed()',
    'teamDefeatedTech()',
    'teamWipedOut()',
    'teamVictory()',
  ],

  propertyRef: [
    'height',
    'maxHp',
    'hp',
    'ammo',
    'maxShield',
    'maxEnergy',
    'ammoIncludingQueued',
    'energy',
    'energyIncludingQueued',
    'shield',
    'kills',
    'queueSize',
    'teamId',
    'x',
    'y',
    'z',
    'dir',
    'priceCredits',
    'tags',
    'transportingCount',
    'numberOfAttachedUnits',
    'timeAlive',
    'lastConverted',
    'customTimer',
    'numberOfUnitsInTeam',
    'numberOfUnitsInAllyNotOwnTeam',
    'numberOfUnitsInEnemyTeam',
    'numberOfUnitsInNeutralTeam',
    'numberOfUnitsInAggressiveTeam',
    'numberOfUnitsInAllTeams',
    'numberOfQueuedWaypoints',
    'speed',
    'maxspeed',
    'builtAmount',
    'maxMoveSpeed',
    'numberOfConnections',
  ],

  //functions
  function: [
    'distance(,,,)',
    'distanceSquared(,,,)',
    'distanceBetween(,)',
    'distanceBetweenSquared(,)',
    'game.nukesEnabled()',
    'int()',
    'select(,,)',
    'debug(,)',
    'debugPassthrough(,)',
    'str()',
    'substring(,,)',
    'length',
    'squareRoot()',
    'min(,)',
    'max(,)',
    'cos()',
    'sin()',
    'uppercase()',
    'lowercase()',
    'direction()',
    'directionBetween()',
    'rnd(,)',
    'mapWidth',
    'mapHeight',
    'thisActionIndex/index',
    'thisActionTarget',
    'eventSource',
  ],
}

const valueType = {
  //Common Values
  true: ['bool', ''],
  false: ['bool', ''],
  if: ['control', ''],
  not: ['control', ''],
  and: ['control', ''],
  or: ['control', ''],

  'isUnderwater()': ['logicBoolean', ''],
  'underwater()': ['logicBoolean', ''],
  'ground()': ['logicBoolean', ''],
  'isAtGroundHeight()': ['logicBoolean', ''],
  'flying()': ['logicBoolean', ''],
  'isFlying()': ['logicBoolean', ''],
  'isMoving()': ['logicBoolean', ''],
  'isAtTopSpeed()': ['logicBoolean', ''],
  'isInWater()': ['logicBoolean', ''],
  'isOverwater()': ['logicBoolean', ''],
  'isOverLiquid()': ['logicBoolean', ''],
  'isOverClift()': ['logicBoolean', ''],
  'isOverPassableTile()': ['logicBoolean', ''],
  'isOverOpenLand()': ['logicBoolean', ''],
  height: ['float', ''],
  'hasResources()': ['logicBoolean', ''],
  'resource()': ['logicBoolean', ''],
  'isResourceLargerThan()': ['logicBoolean', ''],
  maxHp: ['int', ''],
  hp: ['int', ''],
  ammo: ['int', ''],
  maxShield: ['int', ''],
  maxEnergy: ['int', ''],
  'isEnergyRecharging()': ['logicBoolean', ''],
  'isAmmoEmpty()': ['logicBoolean', ''],
  ammoIncludingQueued: ['int', ''],
  energy: ['float', ''],
  energyIncludingQueued: ['float', ''],
  'isEnergyFull()': ['logicBoolean', ''],
  'isEnergyEmpty()': ['logicBoolean', ''],
  shield: ['int', ''],
  kills: ['int', ''],
  queueSize: ['int', ''],
  teamId: ['int', ''],
  x: ['float', ''],
  y: ['float', ''],
  z: ['float', ''],
  dir: ['float', ''],
  priceCredits: ['int', ''],
  'hasFlag()': ['logicBoolean', ''],
  tags: ['string', ''],
  'hasTags()': ['logicBoolean', ''],
  'globalTeamTags()': ['logicBoolean', ''],
  transportingCount: ['int', ''],
  numberOfAttachedUnits: ['int', ''],
  'isAttacking()': ['logicBoolean', ''],
  'hasActiveWaypoint()': ['logicBoolean', ''],
  'transportingUnitWithTags()': ['logicBoolean', ''],
  'isTransportUnloading()': ['logicBoolean', ''],
  'hasParent()': ['logicBoolean', ''],
  'hasTakenDamage()': ['logicBoolean', ''],
  timeAlive: ['float', ''],
  lastConverted: ['float', ''],
  customTimer: ['float', ''],
  'isOnNeutralTeam()': ['logicBoolean', ''],
  'numberOfUnitsInTeam()': ['logicBoolean', ''],
  'numberOfUnitsInAllyNotOwnTeam()': ['logicBoolean', ''],
  'numberOfUnitsInEnemyTeam()': ['logicBoolean', ''],
  'numberOfUnitsInNeutralTeam()': ['logicBoolean', ''],
  'numberOfUnitsInAggressiveTeam()': ['logicBoolean', ''],
  'numberOfUnitsInAllTeams()': ['logicBoolean', ''],
  'hasUnitInTeam()': ['logicBoolean', ''],
  'noUnitInTeam()': ['logicBoolean', ''],
  'isInMap()': ['logicBoolean', ''],
  mapWidth: ['int', ''],
  mapHeight: ['int', ''],
  'isReversing()': ['logicBoolean', ''],
  'isControlledByAI()': ['logicBoolean', ''],
  numberOfQueuedWaypoints: ['int', ''],
  speed: ['float', ''],
  maxspeed: ['float', ''],
  builtAmount: ['float', ''],
  'completed()': ['logicBoolean', ''],
  maxMoveSpeed: ['float', ''],
  'teamDefeatedTech()': ['logicBoolean', ''],
  'teamWipedOut()': ['logicBoolean', ''],
  numberOfConnections: ['int', ''],
  'teamVictory()': ['logicBoolean', ''],

  thisActionTarget: ['unitRef', ''],
  eventSource: ['unitRef', ''],
  attachment: ['unitRef', ''],
  transporting: ['unitRef', ''],
  attacking: ['unitRef', ''],
  lastDamagedBy: ['unitRef', ''],
  parent: ['unitRef', ''],
  activeWaypointTarget: ['unitRef', ''],
  customTarget1: ['unitRef', ''],
  customTarget2: ['unitRef', ''],
  nearestUnit: ['unitRef', ''],
  globalSearchForFirstUnit: ['unitRef', ''],
  nullUnit: ['unitRef', ''],
  null: ['unitRef', ''],
  getAsMarker: ['unitRef', ''],
  getOffsetAbsolute: ['unitRef', ''],
  getOffsetRelative: ['unitRef', ''],
  createMarker: ['unitRef', ''],

  //globalFunctions & Functions
  distance: ['floats=>float', ''],
  distanceSquared: ['float=>float', ''],
  distanceBetween: ['units=>float', ''],
  distanceBetweenSquared: ['units=>float', ''],
  'game.nukesEnabled()': ['logicBoolean', ''],
  int: ['float=>int', ''],
  select: ['any=>any', ''],
  debug: ['logicBooleans=>string', ''],
  debugPassthrough: ['logicBoolean=>string', ''],
  str: ['float=>string', ''],
  substring: ['string=>string', ''],
  length: ['string=>int', ''],
  squareRoot: ['float=>float', ''],
  min: ['floats=>float', ''],
  max: ['floats=>float', ''],
  cos: ['float=>float', ''],
  sin: ['float=>float', ''],
  thisActionIndex: ['int', ''],
  index: ['int', ''],
  uppercase: ['string=>string', ''],
  lowercase: ['string=>string', ''],
  direction: ['undefined', ''],
  directionBetween: ['units=>float', ''],
  rnd: ['floats=>float', ''],

  //customValues
  memory: ['any', ''],
  readUnitMemory: ['any', ''],
  eventData: ['any', ''],
}
export { sections, values, valueType }
